mod badges;
mod boards;
mod build;
mod catalog;
mod cheat;
mod emulator;
mod export;
mod import;
mod inspect;
mod logs;
mod monitor;
mod new;
mod postinstall;
mod repl;
mod runtime;
mod shots;
mod test;
mod vfs;

pub use badges::cmd_badges;
pub use boards::cmd_boards;
pub use build::cmd_build;
pub use catalog::{cmd_catalog_list, cmd_catalog_show};
pub use cheat::cmd_cheat;
pub use emulator::cmd_emulator;
pub use export::cmd_export;
pub use import::cmd_import;
pub use inspect::cmd_inspect;
pub use logs::cmd_logs;
pub use monitor::cmd_monitor;
pub use new::cmd_new;
pub use postinstall::cmd_postinstall;
pub use repl::cmd_repl;
pub use runtime::{cmd_exit, cmd_id, cmd_launch, cmd_restart, cmd_screenshot};
pub use shots::cmd_shots_download;
pub use test::cmd_test;
pub use vfs::cmd_vfs;
